In [1]:
import json
import pandas as pd

In [2]:
with open('test.json', encoding='utf-8-sig') as f:
        data = json.load(f)

In [8]:
def restaurant_result(responses):
    df = pd.DataFrame()
    for r in responses["restaurants"]:
        df1 = pd.DataFrame([{'Restaurant Name' : r['restaurant']['name'], 
                             "Address"         : r['restaurant']['location']['address'],
                             "Phone"           : r['restaurant']["phone_numbers"],
                             "Timing"          : r['restaurant']["timings"],
                             "Cuisines"        : r['restaurant']["cuisines"],
                             "Rating"          : r['restaurant']["user_rating"]["aggregate_rating"],
                             "Total Reviews"   : r['restaurant']["all_reviews_count"],
                             "Avg_Cost_for_Two"  : r['restaurant']["average_cost_for_two"],
                             "Comment"         : r['restaurant']["user_rating"]["rating_text"],
                             "Featured_Image"           : r['restaurant']["featured_image"]
                            }])
        
        df = df.append(df1)
        
    df = df.reset_index()
    df = df.drop(["index"], axis=1)
    return df

restaurant_result = restaurant_result(data)

restaurant_result

,Restaurant Name,Address,Phone,Timing,Cuisines,Rating,Total Reviews,Avg_Cost_for_Two,Comment,image
0,Boa Village,"13, Alipur Road, Civil Lines, New Delhi","+91 8375021313, +91 8375091313",11:30 AM to 12:30 AM,"Asian, Japanese, Korean, Chinese, Momos, Thai",4.2,1204,2300,Very Good,https://b.zmtcdn.com/data/pictures/8/18245298/...
1,Pa Pa Ya,"A-3, Select Citywalk, District Centre, Saket, ...","+91 8800002881, +91 8800002882, 011 40502064",12Noon to 1AM (Mon-Sun),"Asian, Chinese, Thai, Japanese",4.9,2272,2500,Excellent,https://b.zmtcdn.com/data/res_imagery/18429148...
2,Plum By Bent Chair,"The Walk, Worldmark 2, Aerocity, New Delhi","+91 7303156444, +91 7303157444, +91 9888367345",12noon – 1am (Mon-Sun),"Chinese, Japanese, Thai, Asian, Beverages",4.6,1584,3000,Excellent,
3,Chew - Pan Asian Cafe,"M-16, 1st Floor, Outer Circle, Connaught Place...",00 1143544999,"12:30PM to 11:30PM (Mon, Tue, Wed, Thu, Sun), ...","Asian, Japanese, Chinese, Thai",4.2,1656,1700,Very Good,https://b.zmtcdn.com/data/pictures/3/305453/61...
4,C.I.A. Call It Asiian,"13 - 16, Narmada Shopping Complex, Near Don Bo...","011 41612211, 011 40041717, +91 9810111661","Closed (Mon),12:30pm – 10pm (Tue-Sun)","Thai, Chinese, Sushi, Momos",4.5,1001,700,Excellent,https://b.zmtcdn.com/data/pictures/6/18617136/...

In [18]:
def budget_group(row):
    if row['Avg_Cost_for_Two'] <300 :
        return 'lesser than 300'
    elif 300 <= row['Avg_Cost_for_Two'] <700 :
        return 'between 300 to 700'
    else:
        return 'more than 700'

In [34]:
def restaurant_budget(dataset, price_budget):
    dataset['Budget'] = dataset.apply(lambda row: budget_group(row),axis=1)
    restaurant_df = dataset[(dataset.Budget == price_budget)]
    restaurant_df = restaurant_df.sort_values(['Rating'], ascending=0)
    restaurant_df = restaurant_df.drop_duplicates()	
    return restaurant_df
    
# restaurant_budget(restaurant_result, 'more than 700')

In [20]:
# df = pd.DataFrame(columns=['Name', "Location"])
df = pd.DataFrame()
for restaurant in data['restaurants']:
#     print(restaurant['restaurant']['name'])
    response = response + "Found " + restaurant['restaurant']['name'] + " in " + restaurant['restaurant']['location']['address'] + "\n"
#     df1 = pd.DataFrame({'Name' : restaurant['restaurant']['name'], "Location" : restaurant['restaurant']['location']['address']}, index=[0])
    df1 = pd.DataFrame([{'Name' : restaurant['restaurant']['name'], "Location" : restaurant['restaurant']['location']['address']}])
    df = df.append(df1)

In [21]:
df = df.reset_index()
df = df.drop(["index"], axis=1)
df.head()

                    Name                                           Location
0            Boa Village            13, Alipur Road, Civil Lines, New Delhi
1               Pa Pa Ya  A-3, Select Citywalk, District Centre, Saket, ...
2     Plum By Bent Chair         The Walk, Worldmark 2, Aerocity, New Delhi
3  Chew - Pan Asian Cafe  M-16, 1st Floor, Outer Circle, Connaught Place...
4  C.I.A. Call It Asiian  13 - 16, Narmada Shopping Complex, Near Don Bo...

In [22]:
cuisines_dict = {'american': 1, 'chinese': 25, 'italian': 55, 'mexican': 73, 'north indian': 50, 'south indian': 85}

In [23]:
# str(cuisines_dict.get(cuisine))
str(cuisines_dict.get("north indian"))

'50'

In [24]:
df45 = restaurant_result[(restaurant_result.Avg_Cost_for_Two > 1700) & (restaurant_result.Avg_Cost_for_Two < 2500)]
df45

,Restaurant Name,Address,Phone,Timing,Cuisines,Rating,Total Reviews,Avg_Cost_for_Two,Comment,image,Budget
0,Boa Village,"13, Alipur Road, Civil Lines, New Delhi","+91 8375021313, +91 8375091313",11:30 AM to 12:30 AM,"Asian, Japanese, Korean, Chinese, Momos, Thai",4.2,1204,2300,Very Good,https://b.zmtcdn.com/data/pictures/8/18245298/...,more than 700

In [31]:
df10 = restaurant_result.copy()
# df10

In [76]:
def restaurant_budget_price(dataset, min_value, max_value):
    dataset = dataset[(dataset.Avg_Cost_for_Two > min_value) & (dataset.Avg_Cost_for_Two < max_value)]
    dataset = dataset.sort_values(by = ['Rating'], ascending = False)
    return dataset

In [77]:
df46 = restaurant_budget_price(restaurant_result.copy(), 700.05 , 3000.05)
df46

,Restaurant Name,Address,Phone,Timing,Cuisines,Rating,Total Reviews,Avg_Cost_for_Two,Comment,image
1,Pa Pa Ya,"A-3, Select Citywalk, District Centre, Saket, ...","+91 8800002881, +91 8800002882, 011 40502064",12Noon to 1AM (Mon-Sun),"Asian, Chinese, Thai, Japanese",4.9,2272,2500,Excellent,https://b.zmtcdn.com/data/res_imagery/18429148...
2,Plum By Bent Chair,"The Walk, Worldmark 2, Aerocity, New Delhi","+91 7303156444, +91 7303157444, +91 9888367345",12noon – 1am (Mon-Sun),"Chinese, Japanese, Thai, Asian, Beverages",4.6,1584,3000,Excellent,
0,Boa Village,"13, Alipur Road, Civil Lines, New Delhi","+91 8375021313, +91 8375091313",11:30 AM to 12:30 AM,"Asian, Japanese, Korean, Chinese, Momos, Thai",4.2,1204,2300,Very Good,https://b.zmtcdn.com/data/pictures/8/18245298/...
3,Chew - Pan Asian Cafe,"M-16, 1st Floor, Outer Circle, Connaught Place...",00 1143544999,"12:30PM to 11:30PM (Mon, Tue, Wed, Thu, Sun), ...","Asian, Japanese, Chinese, Thai",4.2,1656,1700,Very Good,https://b.zmtcdn.com/data/pictures/3/305453/61...

In [32]:
# d_rest = []

In [35]:
#  d_rest.extend(data['restaurants'])

In [37]:
# d_budget = [d_rest_single for d_rest_single in d_rest if
#             ((d_rest_single['restaurant']['average_cost_for_two'] > 700) & 
#              (d_rest_single['restaurant']['average_cost_for_two'] < 2500))]

In [68]:
# d_budget

In [3]:
response = ""
for restaurant in data['restaurants']:
    response = response + "Found " + restaurant['restaurant']['name'] + " in " + restaurant['restaurant']['location']['address'] + "\n"

In [4]:
response

'Found Boa Village in 13, Alipur Road, Civil Lines, New Delhi\nFound Pa Pa Ya in A-3, Select Citywalk, District Centre, Saket, New Delhi\nFound Plum By Bent Chair in The Walk, Worldmark 2, Aerocity, New Delhi\nFound Chew - Pan Asian Cafe in M-16, 1st Floor, Outer Circle, Connaught Place, New Delhi\nFound C.I.A. Call It Asiian in 13 - 16, Narmada Shopping Complex, Near Don Bosco School, Alaknanda Road, Greater Kailash 2 (GK 2), New Delhi\n'

In [74]:
res1 = ""
for restaurant in data['restaurants']:
    res1 += "Found " + restaurant['restaurant']['name'] + " in " + " \n "
#     restaurant['restaurant']['location']['address'] + "\n"

In [75]:
res1

'Found Boa Village in  \n Found Pa Pa Ya in  \n Found Plum By Bent Chair in  \n Found Chew - Pan Asian Cafe in  \n Found C.I.A. Call It Asiian in  \n '

In [7]:
response = ""
for r in data['restaurants']:
    print("Found " + r['restaurant']['name'] + " in " + r['restaurant']['location']['address'] + "\n")

Found Boa Village in 13, Alipur Road, Civil Lines, New Delhi

Found Pa Pa Ya in A-3, Select Citywalk, District Centre, Saket, New Delhi

Found Plum By Bent Chair in The Walk, Worldmark 2, Aerocity, New Delhi

Found Chew - Pan Asian Cafe in M-16, 1st Floor, Outer Circle, Connaught Place, New Delhi

Found C.I.A. Call It Asiian in 13 - 16, Narmada Shopping Complex, Near Don Bosco School, Alaknanda Road, Greater Kailash 2 (GK 2), New Delhi

In [9]:
restaurant_result

,Restaurant Name,Address,Phone,Timing,Cuisines,Rating,Total Reviews,Avg_Cost_for_Two,Comment,image
0,Boa Village,"13, Alipur Road, Civil Lines, New Delhi","+91 8375021313, +91 8375091313",11:30 AM to 12:30 AM,"Asian, Japanese, Korean, Chinese, Momos, Thai",4.2,1204,2300,Very Good,https://b.zmtcdn.com/data/pictures/8/18245298/...
1,Pa Pa Ya,"A-3, Select Citywalk, District Centre, Saket, ...","+91 8800002881, +91 8800002882, 011 40502064",12Noon to 1AM (Mon-Sun),"Asian, Chinese, Thai, Japanese",4.9,2272,2500,Excellent,https://b.zmtcdn.com/data/res_imagery/18429148...
2,Plum By Bent Chair,"The Walk, Worldmark 2, Aerocity, New Delhi","+91 7303156444, +91 7303157444, +91 9888367345",12noon – 1am (Mon-Sun),"Chinese, Japanese, Thai, Asian, Beverages",4.6,1584,3000,Excellent,
3,Chew - Pan Asian Cafe,"M-16, 1st Floor, Outer Circle, Connaught Place...",00 1143544999,"12:30PM to 11:30PM (Mon, Tue, Wed, Thu, Sun), ...","Asian, Japanese, Chinese, Thai",4.2,1656,1700,Very Good,https://b.zmtcdn.com/data/pictures/3/305453/61...
4,C.I.A. Call It Asiian,"13 - 16, Narmada Shopping Complex, Near Don Bo...","011 41612211, 011 40041717, +91 9810111661","Closed (Mon),12:30pm – 10pm (Tue-Sun)","Thai, Chinese, Sushi, Momos",4.5,1001,700,Excellent,https://b.zmtcdn.com/data/pictures/6/18617136/...

In [100]:
df = restaurant_result.head(10)
df.columns

Index(['Restaurant Name', 'Address', 'Phone', 'Timing', 'Cuisines', 'Rating',
       'Total Reviews', 'Avg_Cost_for_Two', 'Comment', 'image'],
      dtype='object')

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Restaurant Name   5 non-null      object
 1   Address           5 non-null      object
 2   Phone             5 non-null      object
 3   Timing            5 non-null      object
 4   Cuisines          5 non-null      object
 5   Rating            5 non-null      object
 6   Total Reviews     5 non-null      int64
 7   Avg_Cost_for_Two  5 non-null      int64
 8   Comment           5 non-null      object
 9   image             5 non-null      object
dtypes: int64(2), object(8)
memory usage: 528.0+ bytes

In [89]:
response = ""
for ind, val in df.iterrows():
    response = response + "Restaurant Name : " + df['Restaurant Name'][ind] + " & Address : " + df['Address'][ind] +  " & Rating : " + df["Rating"][ind] + " & Total Riews : " + str(df["Total Reviews"][ind]) + "\n" 
#     print(response)
print(response)

Restaurant Name : Boa Village & Address : 13, Alipur Road, Civil Lines, New Delhi & Rating : 4.2 & Total Riews : 1204
Restaurant Name : Pa Pa Ya & Address : A-3, Select Citywalk, District Centre, Saket, New Delhi & Rating : 4.9 & Total Riews : 2272
Restaurant Name : Plum By Bent Chair & Address : The Walk, Worldmark 2, Aerocity, New Delhi & Rating : 4.6 & Total Riews : 1584
Restaurant Name : Chew - Pan Asian Cafe & Address : M-16, 1st Floor, Outer Circle, Connaught Place, New Delhi & Rating : 4.2 & Total Riews : 1656
Restaurant Name : C.I.A. Call It Asiian & Address : 13 - 16, Narmada Shopping Complex, Near Don Bosco School, Alaknanda Road, Greater Kailash 2 (GK 2), New Delhi & Rating : 4.5 & Total Riews : 1001

In [58]:
# print(response)

Restaurant Name : Boa Village & Address : 13, Alipur Road, Civil Lines, New Delhi & Rating : 4.2 & Total Riews : 1204
Restaurant Name : Pa Pa Ya & Address : A-3, Select Citywalk, District Centre, Saket, New Delhi & Rating : 4.9 & Total Riews : 2272
Restaurant Name : Plum By Bent Chair & Address : The Walk, Worldmark 2, Aerocity, New Delhi & Rating : 4.6 & Total Riews : 1584
Restaurant Name : Chew - Pan Asian Cafe & Address : M-16, 1st Floor, Outer Circle, Connaught Place, New Delhi & Rating : 4.2 & Total Riews : 1656
Restaurant Name : C.I.A. Call It Asiian & Address : 13 - 16, Narmada Shopping Complex, Near Don Bosco School, Alaknanda Road, Greater Kailash 2 (GK 2), New Delhi & Rating : 4.5 & Total Riews : 1001

In [98]:
len(data["restaurants"])

5

In [99]:
data["restaurants"]

[{'restaurant': {'R': {'has_menu_status': {'delivery': -1, 'takeaway': -1},
    'res_id': 18245298,
    'is_grocery_store': False},
   'apikey': 'd407d7041129c9c1395aaff316fa6749',
   'id': '18245298',
   'name': 'Boa Village',
   'url': 'https://www.zomato.com/ncr/boa-village-civil-lines-new-delhi?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'location': {'address': '13, Alipur Road, Civil Lines, New Delhi',
    'locality': 'Civil Lines',
    'city': 'New Delhi',
    'city_id': 1,
    'latitude': '28.6766166672',
    'longitude': '77.2252111137',
    'zipcode': '',
    'country_id': 1,
    'locality_verbose': 'Civil Lines, New Delhi'},
   'switch_to_order_menu': 0,
   'cuisines': 'Asian, Japanese, Korean, Chinese, Momos, Thai',
   'timings': '11:30 AM to 12:30 AM',
   'average_cost_for_two': 2300,
   'price_range': 4,
   'currency': 'Rs.',
   'highlights': ['Lunch',
    'Cash',
    'Takeaway Available',
    'Debit Card',
    'Dinner',
    'Delivery',
    'Credit Card',
    'Indoor Seating',
    'Air Conditioned',
    'Wifi',
    'Live Sports Screening',
    'Fullbar',
    'Live Music',
    'Rooftop',
    'Table Reservation Not Required',
    'Smoking Area',
    'Nightlife'],
   'offers': [],
   'opentable_support': 0,
   'is_zomato_book_res': 0,
   'mezzo_provider': 'OTHER',
   'is_book_form_web_view': 0,
   'book_form_web_view_url': '',
   'book_again_url': '',
   'thumb': 'https://b.zmtcdn.com/data/pictures/8/18245298/bff8c184a35d1cf57a58abac1e96881b.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A',
   'user_rating': {'aggregate_rating': '4.2',
    'rating_text': 'Very Good',
    'rating_color': '5BA829',
    'rating_obj': {'title': {'text': '4.2'},
     'bg_color': {'type': 'lime', 'tint': '700'}},
    'votes': 2561},
   'all_reviews_count': 1204,
   'photos_url': 'https://www.zomato.com/ncr/boa-village-civil-lines-new-delhi/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
   'photo_count': 2817,
   'menu_url': 'https://www.zomato.com/ncr/boa-village-civil-lines-new-delhi/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
   'featured_image': 'https://b.zmtcdn.com/data/pictures/8/18245298/bff8c184a35d1cf57a58abac1e96881b.jpg',
   'medio_provider': 1,
   'has_online_delivery': 1,
   'is_delivering_now': 0,
   'store_type': '',
   'include_bogo_offers': True,
   'deeplink': 'zomato://restaurant/18245298',
   'is_table_reservation_supported': 1,
   'has_table_booking': 1,
   'book_url': 'https://www.zomato.com/ncr/boa-village-civil-lines-new-delhi/book?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'events_url': 'https://www.zomato.com/ncr/boa-village-civil-lines-new-delhi/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'phone_numbers': '+91 8375021313, +91 8375091313',
   'all_reviews': {'reviews': [{'review': []},
     {'review': []},
     {'review': []},
     {'review': []},
     {'review': []}]},
   'establishment': ['Bar'],
   'establishment_types': []}},
 {'restaurant': {'R': {'has_menu_status': {'delivery': -1, 'takeaway': -1},
    'res_id': 18429148,
    'is_grocery_store': False},
   'apikey': 'd407d7041129c9c1395aaff316fa6749',
   'id': '18429148',
   'name': 'Pa Pa Ya',
   'url': 'https://www.zomato.com/ncr/pa-pa-ya-saket-new-delhi?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'location': {'address': 'A-3, Select Citywalk, District Centre, Saket, New Delhi',
    'locality': 'Select Citywalk Mall, Saket',
    'city': 'New Delhi',
    'city_id': 1,
    'latitude': '28.5285368249',
    'longitude': '77.2184998915',
    'zipcode': '',
    'country_id': 1,
    'locality_verbose': 'Select Citywalk Mall, Saket, New Delhi'},
   'switch_to_order_menu': 0,
   'cuisines': 'Asian, Chinese, Thai, Japanese',
   'timings': '12Noon to 1AM (Mon-Sun)',
   'average_cost_for_two': 2500,
   'price_range': 4,
   'currency': 'Rs.',
   'highlights': ['Lunch',
    'Mall Parking',
    'Dinner',
    'Cash',
    'Credit Card',
    'Debit Card',
    'Fullbar',
    'Table booking recommended',
    'Smoking Area',
    'Brunch',
    'Indoor Seating',
    'Air Conditioned'],
   'offers': [],
   'opentable_support': 0,
   'is_zomato_book_res': 0,
   'mezzo_provider': 'OTHER',
   'is_book_form_web_view': 0,
   'book_form_web_view_url': '',
   'book_again_url': '',
   'thumb': 'https://b.zmtcdn.com/data/res_imagery/18429148_RESTAURANT_433edbeec2decc62911522378eca7fa8.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A',
   'user_rating': {'aggregate_rating': '4.9',
    'rating_text': 'Excellent',
    'rating_color': '3F7E00',
    'rating_obj': {'title': {'text': '4.9'},
     'bg_color': {'type': 'lime', 'tint': '800'}},
    'votes': 3909},
   'all_reviews_count': 2272,
   'photos_url': 'https://www.zomato.com/ncr/pa-pa-ya-saket-new-delhi/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
   'photo_count': 8694,
   'menu_url': 'https://www.zomato.com/ncr/pa-pa-ya-saket-new-delhi/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
   'featured_image': 'https://b.zmtcdn.com/data/res_imagery/18429148_RESTAURANT_433edbeec2decc62911522378eca7fa8.jpg',
   'medio_provider': 1,
   'has_online_delivery': 0,
   'is_delivering_now': 0,
   'store_type': '',
   'include_bogo_offers': True,
   'deeplink': 'zomato://restaurant/18429148',
   'is_table_reservation_supported': 1,
   'has_table_booking': 0,
   'events_url': 'https://www.zomato.com/ncr/pa-pa-ya-saket-new-delhi/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'phone_numbers': '+91 8800002881, +91 8800002882, 011 40502064',
   'all_reviews': {'reviews': [{'review': []},
     {'review': []},
     {'review': []},
     {'review': []},
     {'review': []}]},
   'establishment': ['Casual Dining'],
   'establishment_types': []}},
 {'restaurant': {'R': {'has_menu_status': {'delivery': -1, 'takeaway': -1},
    'res_id': 18895645,
    'is_grocery_store': False},
   'apikey': 'd407d7041129c9c1395aaff316fa6749',
   'id': '18895645',
   'name': 'Plum By Bent Chair',
   'url': 'https://www.zomato.com/ncr/plum-by-bent-chair-aerocity-new-delhi?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'location': {'address': 'The Walk, Worldmark 2, Aerocity, New Delhi',
    'locality': 'Aerocity',
    'city': 'New Delhi',
    'city_id': 1,
    'latitude': '28.5515400000',
    'longitude': '77.1227040000',
    'zipcode': '',
    'country_id': 1,
    'locality_verbose': 'Aerocity, New Delhi'},
   'switch_to_order_menu': 0,
   'cuisines': 'Chinese, Japanese, Thai, Asian, Beverages',
   'timings': '12noon – 1am (Mon-Sun)',
   'average_cost_for_two': 3000,
   'price_range': 4,
   'currency': 'Rs.',
   'highlights': ['Dinner',
    'Cash',
    'Delivery',
    'Debit Card',
    'Serves Alcohol',
    'Credit Card',
    'Fullbar',
    'Digital Payments Accepted',
    'Valet Parking Available',
    'Indoor Seating',
    'Air Conditioned',
    'Smoking Area'],
   'offers': [],
   'opentable_support': 0,
   'is_zomato_book_res': 0,
   'mezzo_provider': 'OTHER',
   'is_book_form_web_view': 0,
   'book_form_web_view_url': '',
   'book_again_url': '',
   'thumb': '',
   'user_rating': {'aggregate_rating': '4.6',
    'rating_text': 'Excellent',
    'rating_color': '3F7E00',
    'rating_obj': {'title': {'text': '4.6'},
     'bg_color': {'type': 'lime', 'tint': '800'}},
    'votes': 2293},
   'all_reviews_count': 1584,
   'photos_url': 'https://www.zomato.com/ncr/plum-by-bent-chair-aerocity-new-delhi/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
   'photo_count': 5921,
   'menu_url': 'https://www.zomato.com/ncr/plum-by-bent-chair-aerocity-new-delhi/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
   'featured_image': '',
   'medio_provider': 1,
   'has_online_delivery': 0,
   'is_delivering_now': 0,
   'store_type': '',
   'include_bogo_offers': True,
   'deeplink': 'zomato://restaurant/18895645',
   'is_table_reservation_supported': 1,
   'has_table_booking': 0,
   'events_url': 'https://www.zomato.com/ncr/plum-by-bent-chair-aerocity-new-delhi/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'phone_numbers': '+91 7303156444, +91 7303157444, +91 9888367345',
   'all_reviews': {'reviews': [{'review': []},
     {'review': []},
     {'review': []},
     {'review': []},
     {'review': []}]},
   'establishment': ['Casual Dining'],
   'establishment_types': []}},
 {'restaurant': {'R': {'has_menu_status': {'delivery': -1, 'takeaway': -1},
    'res_id': 305453,
    'is_grocery_store': False},
   'apikey': 'd407d7041129c9c1395aaff316fa6749',
   'id': '305453',
   'name': 'Chew - Pan Asian Cafe',
   'url': 'https://www.zomato.com/ncr/chew-pan-asian-cafe-connaught-place-new-delhi?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'location': {'address': 'M-16, 1st Floor, Outer Circle, Connaught Place, New Delhi',
    'locality': 'Connaught Place',
    'city': 'New Delhi',
    'city_id': 1,
    'latitude': '28.6321282314',
    'longitude': '77.2225741670',
    'zipcode': '',
    'country_id': 1,
    'locality_verbose': 'Connaught Place, New Delhi'},
   'switch_to_order_menu': 0,
   'cuisines': 'Asian, Japanese, Chinese, Thai',
   'timings': '12:30PM to 11:30PM (Mon, Tue, Wed, Thu, Sun), 12:30PM to 12Midnight (Fri-Sat)',
   'average_cost_for_two': 1700,
   'price_range': 3,
   'currency': 'Rs.',
   'highlights': ['Lunch',
    'Cash',
    'Credit Card',
    'Dinner',
    'Delivery',
    'Debit Card',
    'Fullbar',
    'Table booking recommended',
    'Wifi',
    'Indoor Seating',
    'Air Conditioned',
    'Smoking Area'],
   'offers': [],
   'opentable_support': 0,
   'is_zomato_book_res': 0,
   'mezzo_provider': 'OTHER',
   'is_book_form_web_view': 0,
   'book_form_web_view_url': '',
   'book_again_url': '',
   'thumb': 'https://b.zmtcdn.com/data/pictures/3/305453/617ec296f3c5f0fb72b12d61c6952cc9.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A',
   'user_rating': {'aggregate_rating': '4.2',
    'rating_text': 'Very Good',
    'rating_color': '5BA829',
    'rating_obj': {'title': {'text': '4.2'},
     'bg_color': {'type': 'lime', 'tint': '700'}},
    'votes': 3286},
   'all_reviews_count': 1656,
   'photos_url': 'https://www.zomato.com/ncr/chew-pan-asian-cafe-connaught-place-new-delhi/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
   'photo_count': 3378,
   'menu_url': 'https://www.zomato.com/ncr/chew-pan-asian-cafe-connaught-place-new-delhi/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
   'featured_image': 'https://b.zmtcdn.com/data/pictures/3/305453/617ec296f3c5f0fb72b12d61c6952cc9.jpg',
   'medio_provider': 1,
   'has_online_delivery': 1,
   'is_delivering_now': 0,
   'store_type': '',
   'include_bogo_offers': True,
   'deeplink': 'zomato://restaurant/305453',
   'is_table_reservation_supported': 1,
   'has_table_booking': 1,
   'book_url': 'https://www.zomato.com/ncr/chew-pan-asian-cafe-connaught-place-new-delhi/book?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'events_url': 'https://www.zomato.com/ncr/chew-pan-asian-cafe-connaught-place-new-delhi/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'phone_numbers': '00 1143544999',
   'all_reviews': {'reviews': [{'review': []},
     {'review': []},
     {'review': []},
     {'review': []},
     {'review': []}]},
   'establishment': ['Casual Dining'],
   'establishment_types': []}},
 {'restaurant': {'R': {'has_menu_status': {'delivery': 1, 'takeaway': -1},
    'res_id': 18617136,
    'is_grocery_store': False},
   'apikey': 'd407d7041129c9c1395aaff316fa6749',
   'id': '18617136',
   'name': 'C.I.A. Call It Asiian',
   'url': 'https://www.zomato.com/ncr/c-i-a-call-it-asiian-greater-kailash-gk-2-new-delhi?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'location': {'address': '13 - 16, Narmada Shopping Complex, Near Don Bosco School, Alaknanda Road, Greater Kailash 2 (GK 2), New Delhi',
    'locality': 'Greater Kailash 2 (GK2)',
    'city': 'New Delhi',
    'city_id': 1,
    'latitude': '28.5277497398',
    'longitude': '77.2467817739',
    'zipcode': '110019',
    'country_id': 1,
    'locality_verbose': 'Greater Kailash 2 (GK2), New Delhi'},
   'switch_to_order_menu': 0,
   'cuisines': 'Thai, Chinese, Sushi, Momos',
   'timings': 'Closed (Mon),12:30pm – 10pm (Tue-Sun)',
   'average_cost_for_two': 700,
   'price_range': 2,
   'currency': 'Rs.',
   'highlights': ['Dinner',
    'Cash',
    'Delivery',
    'Credit Card',
    'Lunch',
    'Takeaway Available',
    'Debit Card',
    'Outdoor Seating',
    'Air Conditioned',
    'Wifi'],
   'offers': [],
   'opentable_support': 0,
   'is_zomato_book_res': 0,
   'mezzo_provider': 'OTHER',
   'is_book_form_web_view': 0,
   'book_form_web_view_url': '',
   'book_again_url': '',
   'thumb': 'https://b.zmtcdn.com/data/pictures/6/18617136/6d81214e6ca48a062a71c7583245487e.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A',
   'user_rating': {'aggregate_rating': '4.5',
    'rating_text': 'Excellent',
    'rating_color': '3F7E00',
    'rating_obj': {'title': {'text': '4.5'},
     'bg_color': {'type': 'lime', 'tint': '700'}},
    'votes': 9310},
   'all_reviews_count': 1001,
   'photos_url': 'https://www.zomato.com/ncr/c-i-a-call-it-asiian-greater-kailash-gk-2-new-delhi/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
   'photo_count': 1627,
   'menu_url': 'https://www.zomato.com/ncr/c-i-a-call-it-asiian-greater-kailash-gk-2-new-delhi/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
   'featured_image': 'https://b.zmtcdn.com/data/pictures/6/18617136/6d81214e6ca48a062a71c7583245487e.jpg',
   'has_online_delivery': 1,
   'is_delivering_now': 1,
   'store_type': '',
   'include_bogo_offers': True,
   'deeplink': 'zomato://restaurant/18617136',
   'order_url': 'https://www.zomato.com/ncr/c-i-a-call-it-asiian-greater-kailash-gk-2-new-delhi/order?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'order_deeplink': '',
   'is_table_reservation_supported': 0,
   'has_table_booking': 0,
   'events_url': 'https://www.zomato.com/ncr/c-i-a-call-it-asiian-greater-kailash-gk-2-new-delhi/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'phone_numbers': '011 41612211, 011 40041717, +91 9810111661',
   'all_reviews': {'reviews': [{'review': []},
     {'review': []},
     {'review': []},
     {'review': []},
     {'review': []}]},
   'establishment': ['Casual Dining'],
   'establishment_types': []}}]

In [94]:
# from concurrent.futures import ThreadPoolExecutor

In [93]:
restaurant_result[:20]

,Restaurant Name,Address,Phone,Timing,Cuisines,Rating,Total Reviews,Avg_Cost_for_Two,Comment,image
0,Boa Village,"13, Alipur Road, Civil Lines, New Delhi","+91 8375021313, +91 8375091313",11:30 AM to 12:30 AM,"Asian, Japanese, Korean, Chinese, Momos, Thai",4.2,1204,2300,Very Good,https://b.zmtcdn.com/data/pictures/8/18245298/...
1,Pa Pa Ya,"A-3, Select Citywalk, District Centre, Saket, ...","+91 8800002881, +91 8800002882, 011 40502064",12Noon to 1AM (Mon-Sun),"Asian, Chinese, Thai, Japanese",4.9,2272,2500,Excellent,https://b.zmtcdn.com/data/res_imagery/18429148...
2,Plum By Bent Chair,"The Walk, Worldmark 2, Aerocity, New Delhi","+91 7303156444, +91 7303157444, +91 9888367345",12noon – 1am (Mon-Sun),"Chinese, Japanese, Thai, Asian, Beverages",4.6,1584,3000,Excellent,
3,Chew - Pan Asian Cafe,"M-16, 1st Floor, Outer Circle, Connaught Place...",00 1143544999,"12:30PM to 11:30PM (Mon, Tue, Wed, Thu, Sun), ...","Asian, Japanese, Chinese, Thai",4.2,1656,1700,Very Good,https://b.zmtcdn.com/data/pictures/3/305453/61...
4,C.I.A. Call It Asiian,"13 - 16, Narmada Shopping Complex, Near Don Bo...","011 41612211, 011 40041717, +91 9810111661","Closed (Mon),12:30pm – 10pm (Tue-Sun)","Thai, Chinese, Sushi, Momos",4.5,1001,700,Excellent,https://b.zmtcdn.com/data/pictures/6/18617136/...

In [90]:
def budget_price(price_value):
	if price_value == "Lesser than Rs. 300":
		budgetmin = 0
		budgetmax = 300
		return budgetmin, budgetmax
	elif price_value == "Rs. 300 to 700":
		budgetmin = 300
		budgetmax = 700
		return budgetmin, budgetmax
	elif price_value == "More than Rs. 700":
		budgetmin = 700
		budgetmax = 10000
		return budgetmin, budgetmax

In [91]:
len(data)

4